# Generated by Django 5.0 on 2023-12-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="headspace",
            name="name",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
